name: Deploy to Frontend

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    # Login to Amazon ECR
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    # Build Docker image
    - name: Build Docker Image
      run: docker build -t my-next-js-appp:06 ./server

    # Tag Docker image for ECR
    - name: Tag Docker Image
      run: docker tag my-next-js-appp:06 767397732220.dkr.ecr.ap-south-1.amazonaws.com/my-next-js-appp:06

    # Push Docker image to Amazon ECR
    - name: Push Docker Image to ECR
      run: docker push 767397732220.dkr.ecr.ap-south-1.amazonaws.com/my-next-js-appp:06

    # Optionally pull the image to verify it is uploaded
    - name: Pull Docker Image from ECR
      run: docker pull 767397732220.dkr.ecr.ap-south-1.amazonaws.com/my-next-js-appp:06

    # Optionally run the container to ensure it works
    - name: Run Docker Container
      run: docker run -d --rm --name myapop -p 3000:3000 767397732220.dkr.ecr.ap-south-1.amazonaws.com/my-next-js-appp:06
